apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "my-copilot"
  namespace: "aura"
  labels:
    "team": "aura"
  annotations:
    "nais.io/run-as-group": "65532"
    "nais.io/run-as-user": "65532"
spec:
  image: {{image}}
  port: 3000
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
      - /_next/**
      - /*.svg
      - /favicon.ico
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
  env:
    - name: "NODE_ENV"
      value: "production"
    - name: "NEXT_TELEMETRY_DISABLED"
      value: "1"
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_METRICS_ENABLED
      value: "true"
    - name: OTEL_METRICS_EXEMPLAR_FILTER
      value: ALWAYS_ON
  liveness:
    path: "/"
    port: 3000
  readiness:
    path: "/"
    port: 3000
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: false
    path: "/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  accessPolicy:
    outbound:
      rules:
        - application: flaky-service
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}