apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "my-copilot"
  namespace: "nais"
  labels:
    "team": "nais"
  annotations:
    "nais.io/run-as-group": "65532"
    "nais.io/run-as-user": "65532"
spec:
  image: {{image}}
  port: 3000
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        groups:
          - id: 48120347-8582-4329-8673-7beb3ed6ca06
          - id: 76e9ee7e-2cd1-4814-b199-6c0be007d7b4
          - id: eb5c5556-6c9a-4e54-83fc-f70cae25358d
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
      - /_next/**
      - /*.svg
      - /favicon.ico
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
  envFrom:
    - secret: my-copilot
  env:
    - name: "NODE_ENV"
      value: "production"
    - name: "GITHUB_ORG"
      value: "navikt"
    - name: "NEXT_TELEMETRY_DISABLED"
      value: "1"
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_METRICS_ENABLED
      value: "true"
    - name: OTEL_METRICS_EXEMPLAR_FILTER
      value: ALWAYS_ON
  liveness:
    path: "/"
    port: 3000
    path: "/health"
  readiness:
    path: "/"
    port: 3000
    path: "/health"
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  accessPolicy:
    outbound:
      rules:
        - application: flaky-service
      external:
        - host: login.microsoftonline.com
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}