namespace: copilot
team: copilot
image: "{{image}}"
replicas_min: 2
replicas_max: 4
memory_limit: 256Mi
cpu_request: 100m
memory_request: 128Mi
ingresses:
  - https://mcp-onboarding.intern.nav.no
base_url: https://mcp-onboarding.intern.nav.no
allowed_organization: navikt
log_level: INFO
