import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@navikt/ds-css";
import "./globals.css";
import { InternalHeader, InternalHeaderTitle, InternalHeaderUser } from "@navikt/ds-react/InternalHeader";
import { Spacer } from "@navikt/ds-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <InternalHeader>
          <InternalHeaderTitle as="h1">Min Copilot</InternalHeaderTitle>
          <Spacer />
          <InternalHeaderUser name="Ola Normann" />
        </InternalHeader>
        {children}
      </body>
    </html>
  );
}