version: "2"

run:
  timeout: 5m
  tests: true

issues:
  exclude-files:
    - '^.+_test\.go$'

linters:
  enable:
    - errcheck
    #- gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    #- gofmt
    #- goimports
    - misspell
    - revive
    - bodyclose
    - errname
    - gocritic
    - gosec
    - nilerr
    - unconvert

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  govet:
    enable-all: true
    disable:
      - fieldalignment

  staticcheck:
    checks: ["all"]

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G104

  exclude-rules:
    - path: _test\.go
      text: "Error return value of `os\\.(Setenv|Unsetenv)` is not checked"
      linters:
        - errcheck

    - path: _test\.go
      text: "Error return value of.*Body\\.Close"
      linters:
        - errcheck

    - path: _test\.go
      linters:
        - gosec
