apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mcp-registry
  namespace: copilot
  labels:
    team: copilot
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: {{cpu_threshold}}
  resources:
    limits:
      memory: {{memory_limit}}
    requests:
      cpu: {{cpu_request}}
      memory: {{memory_request}}
  liveness:
    path: /health
    initialDelay: 30
    timeout: 5
  readiness:
    path: /ready
    initialDelay: 10
    timeout: 5
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: PORT
      value: "8080"
    - name: LOG_LEVEL
      value: "INFO"
    - name: DOMAIN_INTERNAL
      value: "{{domain_internal}}"
    - name: DOMAIN_EXTERNAL
      value: "{{domain_external}}"
    - name: LOGGED_ENDPOINTS
      value: "/,/v0.1/servers"
    - name: SERVICE_NAME
      value: "mcp-registry"
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
